### ISSUE TITLE
Rails 3.1 incompatible?

### ISSUE THREAD

**Issue by millisami** [schneems/likeable#5]
Tried to use in Rails 3.1 app but blows up on `Likeable.setup ...` method in initializer folder

``` rb
/Users/millisami/gitcodes/Likeable/lib/likeable/module_methods.rb:107:in `block in include_in_class': undefined local variable or method `config' for Rails::Application:Class (NameError)
    from /Users/millisami/gitcodes/Likeable/lib/likeable/module_methods.rb:106:in `class_eval'
    from /Users/millisami/gitcodes/Likeable/lib/likeable/module_methods.rb:106:in `include_in_class'
```

**Comment by schneems** [comment]
is this from the example application https://github.com/schneems/likeable_example ? Can you give me your full initializer?

**Comment by millisami** [comment]
Its just a simple rails 3.1.0 app. 

In Gemfile:

```
...
gem rails, '3.1.0' 
gem likeable, '0.0.5'
...
```

The initializer file `config/initializers/likeable.rb` just have the following default config:

``` rb
Likeable.setup do |likeable|
  likeable.redis = Redis.new
end
```

And the backtrace is when I start the server:

```
be rails s                                                                                            ruby-1.9.2-p180
=> Booting WEBrick
=> Rails 3.1.0 application starting in development on http://0.0.0.0:3000
=> Call with -d to detach
=> Ctrl-C to shutdown server
Exiting
/Users/millisami/.rvm/gems/ruby-1.9.2-p180/gems/likeable-0.0.5/lib/likeable/module_methods.rb:107:in `block in include_in_class': undefined local variable or method `config' for Rails::Application:Class (NameError)
    from /Users/millisami/.rvm/gems/ruby-1.9.2-p180/gems/likeable-0.0.5/lib/likeable/module_methods.rb:106:in `class_eval'
    from /Users/millisami/.rvm/gems/ruby-1.9.2-p180/gems/likeable-0.0.5/lib/likeable/module_methods.rb:106:in `include_in_class'
    from /Users/millisami/.rvm/gems/ruby-1.9.2-p180/gems/likeable-0.0.5/lib/likeable/module_methods.rb:123:in `give_users_like_ability'
    from /Users/millisami/.rvm/gems/ruby-1.9.2-p180/gems/likeable-0.0.5/lib/likeable/module_methods.rb:129:in `setup'
    from /Users/millisami/apps/tagliners/config/initializers/likeable.rb:3:in `<top (required)>'
    from /Users/millisami/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:234:in `load'
    from /Users/millisami/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:234:in `block in load'
    from /Users/millisami/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:223:in `block in load_dependency'
    from /Users/millisami/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:640:in `new_constants_in'
    from /Users/millisami/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:223:in `load_dependency'
    from /Users/millisami/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:234:in `load'
    from /Users/millisami/.rvm/gems/ruby-1.9.2-p180/gems/railties-3.1.0/lib/rails/engine.rb:555:in `block (2 levels) in <class:Engine>'
    from /Users/millisami/.rvm/gems/ruby-1.9.2-p180/gems/railties-3.1.0/lib/rails/engine.rb:554:in `each'
    from /Users/millisami/.rvm/gems/ruby-1.9.2-p180/gems/railties-3.1.0/lib/rails/engine.rb:554:in `block in <class:Engine>'
    from /Users/millisami/.rvm/gems/ruby-1.9.2-p180/gems/railties-3.1.0/lib/rails/initializable.rb:25:in `instance_exec'
    from /Users/millisami/.rvm/gems/ruby-1.9.2-p180/gems/railties-3.1.0/lib/rails/initializable.rb:25:in `run'
    from /Users/millisami/.rvm/gems/ruby-1.9.2-p180/gems/railties-3.1.0/lib/rails/initializable.rb:50:in `block in run_initializers'
    from /Users/millisami/.rvm/gems/ruby-1.9.2-p180/gems/railties-3.1.0/lib/rails/initializable.rb:49:in `each'
    from /Users/millisami/.rvm/gems/ruby-1.9.2-p180/gems/railties-3.1.0/lib/rails/initializable.rb:49:in `run_initializers'
    from /Users/millisami/.rvm/gems/ruby-1.9.2-p180/gems/railties-3.1.0/lib/rails/application.rb:92:in `initialize!'
    from /Users/millisami/.rvm/gems/ruby-1.9.2-p180/gems/railties-3.1.0/lib/rails/railtie/configurable.rb:30:in `method_missing'
    from /Users/millisami/apps/tagliners/config/environment.rb:5:in `<top (required)>'
    from /Users/millisami/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:240:in `require'
    from /Users/millisami/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:240:in `block in require'
    from /Users/millisami/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:223:in `block in load_dependency'
    from /Users/millisami/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:640:in `new_constants_in'
    from /Users/millisami/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:223:in `load_dependency'
    from /Users/millisami/.rvm/gems/ruby-1.9.2-p180/gems/activesupport-3.1.0/lib/active_support/dependencies.rb:240:in `require'
    from /Users/millisami/apps/tagliners/config.ru:4:in `block in <main>'
    from /Users/millisami/.rvm/gems/ruby-1.9.2-p180/gems/rack-1.3.5/lib/rack/builder.rb:51:in `instance_eval'
    from /Users/millisami/.rvm/gems/ruby-1.9.2-p180/gems/rack-1.3.5/lib/rack/builder.rb:51:in `initialize'
    from /Users/millisami/apps/tagliners/config.ru:1:in `new'
    from /Users/millisami/apps/tagliners/config.ru:1:in `<main>'
    from /Users/millisami/.rvm/gems/ruby-1.9.2-p180/gems/rack-1.3.5/lib/rack/builder.rb:40:in `eval'
    from /Users/millisami/.rvm/gems/ruby-1.9.2-p180/gems/rack-1.3.5/lib/rack/builder.rb:40:in `parse_file'
    from /Users/millisami/.rvm/gems/ruby-1.9.2-p180/gems/rack-1.3.5/lib/rack/server.rb:200:in `app'
    from /Users/millisami/.rvm/gems/ruby-1.9.2-p180/gems/railties-3.1.0/lib/rails/commands/server.rb:46:in `app'
    from /Users/millisami/.rvm/gems/ruby-1.9.2-p180/gems/rack-1.3.5/lib/rack/server.rb:301:in `wrapped_app'
    from /Users/millisami/.rvm/gems/ruby-1.9.2-p180/gems/rack-1.3.5/lib/rack/server.rb:252:in `start'
    from /Users/millisami/.rvm/gems/ruby-1.9.2-p180/gems/railties-3.1.0/lib/rails/commands/server.rb:70:in `start'
    from /Users/millisami/.rvm/gems/ruby-1.9.2-p180/gems/railties-3.1.0/lib/rails/commands.rb:54:in `block in <top (required)>'
    from /Users/millisami/.rvm/gems/ruby-1.9.2-p180/gems/railties-3.1.0/lib/rails/commands.rb:49:in `tap'
    from /Users/millisami/.rvm/gems/ruby-1.9.2-p180/gems/railties-3.1.0/lib/rails/commands.rb:49:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'
```

**Comment by schneems** [comment]
i cut a new gem 0.1.0 that should fix this problem and a few others, can you please try the new version? If you're still having problems we can re-open the issue
